author: eccentric_nz
description: Allows you to store your XP by clicking on a special sign
main: me.eccentric_nz.plugins.xpkeeper.XPKeeper
dev-url: http://de.bukkit.org/server-mods/xpkeeper/
name: XPKeeper
startup: postworld
version: '1.4.0'
permissions:
  xpkeeper.use:
    description: Allow players to use XPKeeper signs
    default: op
  xpkeeper.fist:
    description: Allow players to toggle must_use_fist true|false
    default: op
  xpkeeper.limit:
    description: Allow players to toggle set_limits true|false
    default: op
  xpkeeper.limit.bypass:
    description: Allow players to bypass limits
    default: op
  xpkeeper.force:
    description: Allow players to force remove player data
    default: op
  xpkeeper.admin:
    description: Allow players to set/give XP
    default: op
  xpkeeper.editsign:
    description: Allow players to edit signs
    default: op
commands:
  xpkgive:
    aliases: [xpkg]
    description: Give a player some XP.
    usage: /<command> [player] [amount]
  xpkset:
    aliases: [xpks]
    description: Set a player's total XP.
    usage: /<command> [player] [amount]
  xpkremove:
    aliases: [xpkr, xpkrem]
    description: Remove an XPKeeper sign.
    usage: /<command>
  xpkforceremove:
    aliases: [xpkfr, xpkforce]
    description: Remove ALL player data from the database - use with caution.
    usage: /<command> [player]
  xpkfist:
    aliases: [xpkf]
    description: Toggle the XPKeeper must_use_fist config option.
    usage: /<command>
  xpkedit:
    aliases: [xpke]
    description: Edit the first line of the XPKeeper sign.
    usage: /<command>
  xpkpay:
    aliases: [xpkp]
    description: Pay another player some XP.
    usage: /<command> [player] [amount]
  xpkwithdraw:
    aliases: [xpkw, xpkwd]
    description: Set the amount, in levels, that is withdrawn from an XPKeeper sign. 0 = all.
    usage: /<command> [amount]
  xpklimit:
    aliases: [xpkl]
    description: Toggle the XPKeeper set_limits config option.
    usage: /<command>
  xpkreload:
    aliases: [xpkrl]
    description: Reloads the config file.
    usage: /<command>
  xpkcolour:
    aliases: [xpkc,xpkcolor]
    description: Sets 'firstline_colour' in the config file.
    usage: /<command> [colour code e.g. &6]
